### ISSUE TITLE
client should be able to opt-out from 200ms wait time

### ISSUE THREAD

**Issue by Wojtus11** [pawelkn/xapi-python#2]
class Connection():
[snip]
    async def disable_wait_for_next_call(self):
        self._last_request_time = None0

**Comment by pawelkn** [comment]
Good idea! I'll add the proposed code to the Connection class:

```python
def skip_delay(self):
    """Dispatch the next request without the 200ms delay"""
    self._last_request_time = None
```

**Comment by pawelkn** [comment]
Added in v0.1.7
