### ISSUE TITLE
getCandles

### ISSUE THREAD

**Issue by idrys** [pawelkn/xapi-python#3]
As I understand it, it should return results every 1 minute. Unfortunately, no data is coming in, and I'm not receiving any error or session disconnection information either. Am I correct in assuming that the XTB operator has stopped sending data in response to this request?

**Comment by pawelkn** [comment]
I've checked the example `python3 examples/get-candles.py`. It works fine. Maybe you are trying to get candles during the closed market?

**Comment by sgflt** [comment]
I haven't received any candle since 16. 5. 2024. I am using demo websokcet URL: wss://ws.xtb.com/demoStream.

Workaround that may be related https://github.com/peterszombati/xapi-node/issues/17

**Comment by sgflt** [comment]
Trick with getLastChart works.

**Comment by pawelkn** [comment]
Use a `real` account, not a `demo` one, to stream candles and let me know if the problem persists. There may be account type related issues. 

You can also try the `getTickPrices` stream as an alternative. I have been using the `getTickPrices` stream for over a year and it is very stable.

**Comment by sgflt** [comment]
getTickPrices it requires some manual aggregations, but yes, it works.

**Comment by htimi** [comment]
Hello hello, i have the same issue with getCandles command for xtb. Using xapi-python or not. 
I contact the support no answer yet. couple days ago i get candles only for bitcoin now nothing wait for the support.

**Comment by pawelkn** [comment]
This bug is host related. There is nothing we can do on the client side.
