### ISSUE TITLE
Close transaction throws error

### ISSUE THREAD

**Issue by HammerMonkey** [pawelkn/xapi-python#4]
Hello,
Thanks for this Library!
While working on it I hit the issue, I cannot Close opened transaction, here is my code:
open_trades = await x.socket.getTrades(openedOnly=True)
open_trades = open_trades["returnData"]
for trade in open_trades:
    response = await x.socket.tradeTransaction(
                            symbol=trade['symbol'],
                            cmd=xapi.TradeCmd(value=trade['cmd']),
                            type=xapi.TradeType.CLOSE,
                            price=trade['close_price'],
                            volume=trade['volume'],
                            order=trade['order'],
                        )
API returns error:
{'status': False, 'errorCode': 'SE199', 'errorDescr': 'Internal error'}
any suggestions?

**Comment by HighVoltageCoder** [comment]
Print returned data and paste it :) . Are you sure it is returning something?

**Comment by HammerMonkey** [comment]
the returned data is:
{'status': False, 'errorCode': 'SE199', 'errorDescr': 'Internal error'}

**Comment by HighVoltageCoder** [comment]
I mean the orders_trade dictionary

**Comment by HammerMonkey** [comment]
Everything else works fine. here is my open_trades:
[{'cmd': 0, 'order': 627748153, 'digits': 2, 'offset': 0, 'order2': 627726330, 'position': 627748153, 'symbol': 'MSFT.US_9', 'comment': '', 'customComment': None, 'commission': 0.0, 'storage': 0.0, 'margin_rate': 0.0, 'close_price': 440.15, 'open_price': 426.57, 'nominalValue': 172.77, 'profit': 2.81, 'volume': 0.1, 'sl': 0.0, 'tp': 0.0, 'closed': False, 'timestamp': 1718223100691, 'spread': 0, 'taxes': 0.0, 'open_time': 1718030732761, 'open_timeString': 'Mon Jun 10 16:45:32 CEST 2024', 'close_time': None, 'close_timeString': None, 'expiration': None, 'expirationString': None}, {'cmd': 0, 'order': 
628542401, 'digits': 2, 'offset': 0, 'order2': 628542355, 'position': 628542401, 'symbol': 'MSFT.US_9', 'comment': '', 'customComment': '', 'commission': 0.0, 'storage': 0.0, 'margin_rate': 0.0, 'close_price': 440.15, 'open_price': 438.5, 'nominalValue': 175.9, 'profit': -0.32, 'volume': 0.1, 'sl': 0.0, 'tp': 0.0, 'closed': False, 'timestamp': 1718223100691, 'spread': 0, 'taxes': 0.0, 'open_time': 1718210689500, 'open_timeString': 'Wed Jun 12 18:44:49 CEST 2024', 'close_time': None, 'close_timeString': None, 'expiration': None, 'expirationString': None}]

**Comment by HighVoltageCoder** [comment]
`if side_to_close == xapi.TradeCmd.SELL:
            cmd = xapi.TradeCmd.BUY
            price = self.tick_record.ask
        if side_to_close == xapi.TradeCmd.BUY:
            cmd = xapi.TradeCmd.SELL
            price = self.tick_record.bid
        
        response = await x.socket.tradeTransaction(
                symbol=self.symbol_to_trade,
                order=order.order,
                cmd=cmd,
                type=xapi.TradeType.CLOSE,
                price=price,
                volume=order.volume,
                sl=0.0,
                tp=0.0,
                customComment='Emergency Close'
            )
`
I have this code to close position.
Maybe it will help you.

I think that you have problem with CMD in your code.

**Comment by pawelkn** [comment]
To close an open buy position, you must create (open) a new sell transaction. Do not enter the position order number for the sell transaction. It is the new transaction and will have a unique order number:

```python
response = await x.socket.tradeTransaction(
   symbol=trade['symbol'],
   cmd=xapi.TradeCmd.SELL,
   type=xapi.TradeType.OPEN,
   price=trade['close_price'],
   volume=trade['volume']
)
```

or with price limit:

```python
response = await x.socket.tradeTransaction(
   symbol=trade['symbol'],
   cmd=xapi.TradeCmd.SELL_LIMIT,
   type=xapi.TradeType.OPEN,
   price=trade['close_price'],
   volume=trade['volume']
)
```

**Comment by HammerMonkey** [comment]
@pawelkn WORKS! Thank you!

**Comment by HammerMonkey** [comment]
closing
