### ISSUE TITLE
Difference between the real chart in XTB and xapi

### ISSUE THREAD

**Issue by idrys** [pawelkn/xapi-python#5]
Hi, please excuse my ignorance and lack of experience, but how can I explain such a significant difference between what I see on the real chart in XTB and what I get from xapi? EURUSD in XTB bid: 1.8244 and in xapi: bid: 1.08239. Example shown in the screenshot.

---

![Zrzut ekranu 2024-07-31 o 06 51 12](https://github.com/user-attachments/assets/c8958124-a548-452c-ad88-d710539c372e)

**Comment by pawelkn** [comment]
What command do you call?

**Comment by pawelkn** [comment]
I think I know what causes the difference. The API sends ticks with different price levels. While the xStation5 only shows level 0 price:

![Zrzut ekranu 2024-07-31 083143](https://github.com/user-attachments/assets/f1f8d6c1-0a05-4652-a3ca-3bcad3e53d29)

**Comment by idrys** [comment]
Thanks
