### ISSUE TITLE
Installation and Usage

### ISSUE THREAD

**Issue by gastoncs** [pawelkn/xapi-python#7]
HI, 

I did the installation and the first usage example, I am getting the following error, is there anything I am missing?

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 26
     23         print(f"Connection closed: {e}")
     25 if __name__ == "__main__":
---> 26     asyncio.run(main())

File [/opt/conda/lib/python3.11/asyncio/runners.py:186](http://localhost:8889/opt/conda/lib/python3.11/asyncio/runners.py#line=185), in run(main, debug)
    161 """Execute the coroutine and return the result.
    162 
    163 This function runs the passed coroutine, taking care of
   (...)
    182     asyncio.run(main())
    183 """
    184 if events._get_running_loop() is not None:
    185     # fail fast with short traceback
--> 186     raise RuntimeError(
    187         "asyncio.run() cannot be called from a running event loop")
    189 with Runner(debug=debug) as runner:
    190     return runner.run(main)

RuntimeError: asyncio.run() cannot be called from a running event loop`

**Comment by gastoncs** [comment]
Yes

**Comment by gastoncs** [comment]
I am running it directly on my laptop, after installing pip install xapi-python when I run the any of the examples i get the following error

ModuleNotFoundError: No module named 'xapi'

**Comment by pawelkn** [comment]
For future reference. Examples of using xapi-python in Jupyter Notebook:

https://github.com/pawelkn/xapi-python/blob/master/examples/get-margin-level.ipynb
https://github.com/pawelkn/xapi-python/blob/master/examples/get-chart-last-request.ipynb
https://github.com/pawelkn/xapi-python/blob/master/examples/get-chart-range-request.ipynb
